"""more_char_in_short_url

Revision ID: 7c1ebd294bab
Revises: bcce9cce1531
Create Date: 2024-10-22 09:48:02.419989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1ebd294bab'
down_revision = 'bcce9cce1531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'short_url',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.VARCHAR(length=16),
               existing_comment='Сокращенная ссылка',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'short_url',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=5),
               existing_comment='Сокращенная ссылка',
               existing_nullable=True)
    # ### end Alembic commands ###
