"""base_url_table

Revision ID: 7ed80c276b23
Revises: 
Create Date: 2024-10-21 21:54:22.835134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed80c276b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('long_url', sa.TEXT(), nullable=True, comment='Полная ссылка'),
    sa.Column('short_url', sa.VARCHAR(length=5), nullable=True, comment='Сокращенная ссылка'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
