"""url_short_url_idx

Revision ID: bcce9cce1531
Revises: 7ed80c276b23
Create Date: 2024-10-21 21:58:36.184757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcce9cce1531'
down_revision = '7ed80c276b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url_short_url_idx', 'url', ['short_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url_short_url_idx', table_name='url')
    # ### end Alembic commands ###
